# Generated by Django 2.1.5 on 2019-02-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('absences', models.ManyToManyField(to='Account.Profile')),
                ('associated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_session', to='School.Class')),
            ],
        ),
    ]
