# Generated by Django 2.1.5 on 2019-02-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20190218_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
    ]
