# Generated by Django 2.1.5 on 2019-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0007_auto_20190218_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='absences',
            field=models.ManyToManyField(blank=True, to='Account.Profile'),
        ),
    ]
